apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcat-node
  labels:
    app: webcat-node
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webcat-node
  template:
    metadata:
      labels:
        run: webcat-node
    spec:
      containers:
      - name: webcat-node
        image: 333666999/webcat:v559
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webcat-data
          mountPath: /usr/web-cat-storage/
        env:
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: custom-db-username
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: custom-db-password
        - name: POSTFIX_EMAIL
          valueFrom:
            secretKeyRef:
              name: postfix
              key: email
        - name: POSTFIX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postfix
              key: password
      volumes:
      - name: webcat-data
        persistentVolumeClaim:
          claimName: webcat-pvc